services:
  - type: web
    name: torrent-backend
    env: node
    build:
      nodeVersion: 18
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DOWNLOAD_DIR
        value: ./downloads
    plan: free